# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usbhid"
    "sdhci_pci"
  ];

  # Force the exact Live CD dependency chain
  boot.initrd.kernelModules = [
    # Graphics stack (Early KMS to eliminate GDM delay)
    "amdgpu"
    "nvidia"
    "nvidia_modeset"
    "nvidia_uvm"
    "nvidia_drm"

    "usbhid"
    "i8042"
    "i2c_piix4"
    "i2c_hid_acpi"
    "asus_wmi"
    "asus_nb_wmi"
    "hid_asus"
  ];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];
  boot.kernelParams = ["nvidia_drm.fbdev=1"];

  boot.kernelPackages = pkgs.linuxKernel.packages.linux_7_2;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
