# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.kernelModules = ["asus_nb_wmi" "asus_wmi" "hid_asus" "kvm-amd"];

  boot.kernelParams = [ "usbcore.autosuspend=-1" ];
  boot.initrd.availableKernelModules = ["evdev" "hid_asus" "usbhid" "i8042" "atkbd" "nvme" "xhci_pci" "thunderbolt" "sdhci_pci"];
  boot.extraModulePackages = [];

  boot.initrd.systemd.enable = true;
  boot.kernelPackages = pkgs.linuxPackages;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
